### ISSUE TITLE
Bitfield macro trait implementation on struct

### ISSUE THREAD

**Issue by mikart143** [Robbepop/modular-bitfield#48] opened 2020-10-31 12:44 UTC
Does the bitfield macro implement some trait on struct ? I would like to create function which will take such sructs that have bitfield macro. Any ideas ?

**Comment by henrikssn** [comment] 2020-10-31 13:31
Is this a duplicate of #40? Could you please provide an example?

**Comment by Robbepop** [comment] 2020-10-31 13:43
Yes, please provide an example for your use case but in issue #40 . Closed because of duplication.

**Closed by Robbepop** 2020-10-31 13:43 UTC
